=== Sustainedhhh/etl/etl/src/main/xsd/ETL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by TEAM ViRiLiTY (VRL) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ETL">
		<xs:annotation>
			<xs:documentation>ETL Root Element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Declartion"/>
				<xs:element ref="Process" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Process">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Database" minOccurs="0"/>
				<xs:element ref="SOAPWebservice" minOccurs="0"/>
				<xs:element ref="RESTfulWebservice" minOccurs="0"/>
				<xs:element ref="CSV" minOccurs="0"/>
				<xs:element ref="File" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Database">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sql" type="xs:string"/>
				<xs:element ref="Process" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" use="required"/>
			<xs:attribute name="connection-id" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SOAPWebservice">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="URL" type="xs:string"/>
				<xs:element name="Action" type="xs:string"/>
				<xs:element name="Input"/>
				<xs:element ref="Process" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="RESTfulWebservice">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="URL">
					<xs:complexType mixed="true">
						<xs:attribute name="Accept" default="application/*">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="application/*"/>
									<xs:enumeration value="application/xml"/>
									<xs:enumeration value="application/json"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Content-Type" default="application/xml">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="application/*"/>
									<xs:enumeration value="application/xml"/>
									<xs:enumeration value="application/json"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Method"/>
				<xs:element name="Input" minOccurs="0"/>
				<xs:element ref="Process" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CSV">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element name="URL"/>
				<xs:element ref="Process" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FlatFile"/>
	<xs:element name="Declartion">
		<xs:complexType>
			<xs:all>
				<xs:element name="Properties" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property-File" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" use="required"/>
									<xs:attribute name="path" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Connections" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Connection" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropertyFile"/>
	<xs:element name="File">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element name="URL"/>
				<xs:element ref="Process" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Connection">
		<xs:complexType>
			<xs:attribute name="id" use="required"/>
			<xs:attribute name="username" use="required"/>
			<xs:attribute name="password" use="required"/>
			<xs:attribute name="url" use="required"/>
			<xs:attribute name="driver" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sustainedhhh/etl/etl-web/src/test/ETL.xml
<?xml version="1.0" encoding="UTF-8"?>
<ETL xsi:noNamespaceSchemaLocation="../xsd/ETL.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Declartion>
		<Connections>
			<Connection url="jdbc:sqlite:G:\outside-the-box\github\etl\etl.web\src\test\ETL.db" id="etl"
				username="" password="" driver="org.sqlite.JDBC" />
		</Connections>
	</Declartion>
	<Process id="proc1">
		<RESTfulWebservice id="r1">
			<URL>http://localhost:8080/api/Employee</URL>
			<Method>GET</Method>
			<Process id="proc1-child1">
				<Database id="d1" connection-id="etl">
					<sql>INSERT INTO Employee(EMP_ID, NAME) VALUES(?r1./Employees/Employee/ID, '?r1./Employees/Employee/Name')</sql>
				</Database>
				<SOAPWebservice id="s1">
					<Action>http://localhost:8080/Company/services/EmployeeSOAP
					</Action>
					<Input>{file(./Test/SOAP.xml)}</Input>
					<Process id="proc1-child2">
						<Database connection-id="etl" id="d2">
						<sql>SELECT ?s1./id , '?s1./name'</sql>
						</Database>
					</Process>
				</SOAPWebservice>
			</Process>
		</RESTfulWebservice>
	</Process>
</ETL>

=== Sustainedhhh/etl/ETL/Test/ETL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 (http://www.altova.com) -->
<ETL xsi:noNamespaceSchemaLocation="../xsd/ETL.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Declartion>
		<Connections>
			<Connection url="jdbc:sqlite:./Test/ETL.db" id="etl" username=""
				password="" driver="org.sqlite.JDBC" />
		</Connections>
	</Declartion>
	<Process id="proc1">
		<RESTfulWebservice id="r1">
			<URL>http://localhost:8080/Company/api/Employee</URL>
			<Method>GET</Method>
			<Process id="proc1-child1">
				<Database id="d1" connection-id="etl">
					<sql>INSERT INTO Employee(EMP_ID, NAME) VALUES(?r1./Employees/Employee/ID, '?r1./Employees/Employee/Name')</sql>
				</Database>
			</Process>
		</RESTfulWebservice>
	</Process>
</ETL>
